# Generated by Django 4.1.3 on 2022-11-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text='Enter name of car brand', max_length=200, verbose_name='brand')),
                ('model', models.CharField(max_length=200, verbose_name='model')),
                ('year', models.DateField(verbose_name='manufacture year')),
            ],
        ),
    ]
