# Generated by Django 4.1.3 on 2022-11-07 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_nr', models.CharField(help_text='Enter car number', max_length=50, verbose_name='car number')),
                ('vin_code', models.CharField(blank=True, help_text='<a href="https://www.autocheck.com/vehiclehistory/vin-basics" target="_blank">ISBN code</a> consisting of 17 symbols', max_length=17, null=True, verbose_name='VIN code')),
                ('client', models.CharField(max_length=255, verbose_name='cliens name')),
                ('car_model_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservisas.carmodel')),
            ],
        ),
    ]
