# Generated by Django 4.1.3 on 2022-11-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0002_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Write down service name', max_length=255, verbose_name='service name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='price')),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='vin_code',
            field=models.CharField(blank=True, help_text='<a href="https://www.autocheck.com/vehiclehistory/vin-basics" target="_blank">VIN code</a> consisting of 17 symbols', max_length=17, null=True, verbose_name='VIN code'),
        ),
    ]
