# Generated by Django 4.1.3 on 2022-11-07 13:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0003_service_alter_car_vin_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='unique ID')),
                ('date', models.DateField(verbose_name='orders date')),
                ('total_sum', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='price')),
                ('car_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autoservisas.car')),
            ],
        ),
    ]
