# Generated by Django 4.1.3 on 2022-11-07 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0006_rename_car_model_id_car_car_model_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderline',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderline',
            old_name='service_id',
            new_name='service',
        ),
    ]
